name: stream_chat_flutter_core
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK Core. Build your own chat experience using Dart and Flutter.
version: 5.3.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues
publish_to: none # for local imports

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.0
  connectivity_plus: ^3.0.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  meta: ^1.8.0
  rxdart: ^0.27.0
  stream_chat:
    path: ../stream_chat

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.2
  fake_async: ^1.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  mocktail: ^0.3.0

